### ISSUE TITLE
Gmail reconnects twice after disconnection

### ISSUE THREAD

**Issue by raisedintheusa** [dzg/matrix-googlevoice#1]
Hi, bot is working great, only issue I've experienced is after Gmail gets disconnected, it reconnects twice, resulting in messages sent to Voice being output twice on Matrix. A message sent from Matrix to Voice still gets sent once, so the issue is only one-way.

**Comment by dzg** [comment]
Hm, haven't seen this on my end. Is that _after_ getting a `GMAIL: Disconnected, attempting reconnection...` message from the bot?

**Comment by raisedintheusa** [comment]
Yes,
```
[33m GMAIL Error: Error: read ECONNRESET
Attempting reconnection...
🔴 GMAIL: Disconnected, attempting reconnection...
🟢 GMAIL: connected
🟢 GMAIL: connected
```
I'm running the bot on my laptop, which I put to sleep at night, so this happens when I wake it up in the morning.

**Comment by dzg** [comment]
Can you try sending the bot a `!restart` command? LMK what it says. Curious if we get 1 or 2 `connected` messages.

**Comment by dzg** [comment]
Also ... has this behavior been happening since the first time you ran the bot? Or did it just start recently?

**Comment by raisedintheusa** [comment]
`!restart` gives the normal `MATRIX: Connected GMAIL: connected` messages, one for each. I only began running it on Sunday and it happened yesterday morning and this morning.

**Comment by dzg** [comment]
OK, I think I know what the issue was. (At some point a 2nd mail client was started without stopping the first instance.) I pushed a new `matrix-googlevoice-bot.js`  – LMK how it goes!

**Comment by dzg** [comment]
> I'm running the bot on my laptop, which I put to sleep at night, so this happens when I wake it up in the morning.

I'm guessing the sleep cycle causes the mail client to lose its connection to Gmail. Then upon waking up it creates a new connection.

Can you send me the console log from when the laptop wakes up in the morning?

FWIW ... I run my bot on a free [Oracle Cloud](https://cloud.oracle.com/) VM, so no sleeping/waking interruptions. Might be a more stable solution for you.

**Comment by raisedintheusa** [comment]
I ran the updated code, put my computer to sleep for an hour so Gmail would disconnect, woke it back up, and the issue is resolved! Gmail reconnected just once and no further duplicate messages.
Thanks for the cloud VM recommendation, I'll look into that.

**Comment by dzg** [comment]
Awesome. Thanks for finding the bug.
