### ISSUE TITLE
ReferenceError: bodytxt is not defined

### ISSUE THREAD

**Issue by eTomte** [dzg/matrix-googlevoice#5]
Thanks for coding this great project.  I found it last week and was thrilled to see that there might be a way to integrate my GV SMSes with Matrix.

I have the bridge mostly working.  The bridge bot room is created successfully, I can issue commands to the bot user, and they work.  I have the green dots that show that both the matrix side and the gmail side are connected.

The problem happens when a new SMS comes into Gmail.  it does not appear on the Matrix side, and viewing the console messages I see the following error:

2023-01-08 14:32:43 <= '* 1 FETCH (X-GM-THRID 1754484250231752428 X-GM-MSGID 1754487800804978311 X-GM-LABELS ("\\\\Important") UID 47560 MODSEQ (11313397) INTERNALDATE "08-Jan-2023 20:32:34 +0000" FLAGS (\\Seen) )'
2023-01-08 14:32:43 GMAIL (in): {
  "text": "\n<https://voice.google.com>\ntest1\nYOUR ACCOUNT <https://voice.google.com> HELP CENTER\n<https://support.google.com/voice#topic=1707989> HELP FORUM\n<https://productforums.google.com/forum/#!forum/voice>\nThis email was sent to you because you indicated that you'd like to receive\nemail notifications for text messages. If you don't want to receive such\nemails in the future, please update your email notification settings\n<https://voice.google.com/settings#messaging>.\nGoogle LLC\n1600 Amphitheatre Pkwy\nMountain View CA 94043 USA\n",
  "from": {
    "address": "[redacted]",
    "name": "[redacted]"
  },
  "subject": "New text message from [redacted]"
}
/home/me/matrix-googlevoice/matrix-googlevoice-bot.js:273
      data.body = bodytxt.replace(/([a-z])\n/g, '$1 ')
                  ^

ReferenceError: bodytxt is not defined
    at MailListener.<anonymous> (/home/me/matrix-googlevoice/matrix-googlevoice-bot.js:273:19)
    at MailListener.emit (node:events:513:28)
    at EventEmitter.<anonymous> (/home/me/matrix-googlevoice/matrix-googlevoice-bot.js:222:27)

The contents of the text message were "test1"

Is this a known issue?  Did google change something on their side or is this just something that I'm experiencing?

I tried using various versions of node.js to see if that affected the issue.  I get the same issue no matter what version of node.js I'm on.  The only difference is that in node.js node v14.21.2  or lower the error message doesn't cause the process to exit, but in higher versions this error will cause the process to stop because of the exit code. 

But in all cases the error message about "bodytxt is not defined" is the same.

Thanks in advance!

**Comment by dzg** [comment]
Sorry, I haven't touched/looked at this project in a looooooong time ... it "just works" on my end.

If I have time I'll try to dig in your issue, but I can't promise when that will be, as I'm busy with other stuff, sorry!

**Comment by dzg** [comment]
At first glance – my guess is look at line 262:

```js
let body = text.replace(/.*<https:\/\/voice\.google\.com>/im, '').replace(/(To respond to this text message, reply to this email or visit Google Voice|YOUR ACCOUNT <https:\/\/voice\.google\.com>)(.|\n)*/m, '').replace(/Hello.*\n/, '').trim()
```

This is meant to parse the actual message from all the extra Google Garbage. Maybe your emails are slightly different, so `body` is not getting parsed right.

I would tweak this (maybe using something like regexr.com) and get it to boil down your email text ... or as a failsafe, just do  
`let body = text` and see if you get the FULL message content.

Good luck!

**Comment by eTomte** [comment]
Thanks for the quick reply  i replaced the line in question with let bodytxt = text  and now its work (although with all of the google verbiage of course)   :)

**Comment by eTomte** [comment]
my guess is that its some google change that will eventually affect you

in any case thanks for coding this great bridge  :)

**Comment by eTomte** [comment]
I have this working like a champ, now.  Thanks for writing this awesome tool. :)

In the end the only change I needed to make was in line 262, from 

let body = text ......

to

let bodytxt = text ......

Thanks again!

**Comment by fauxpaux** [comment]
Thanks eTomte, this worked for me too
