### ISSUE TITLE
Use of aliasSuffix breaks replies

### ISSUE THREAD

**Issue by BigMace23** [dzg/matrix-googlevoice#9]
I was unable to get replies working until setting the aliasSuffix variable to a blank string in the config file... it looks as if this is also being appended to the recipient email address during reply resulting in an invalid address and failed send.

Just wanted to highlight this for others who may be having similar issues - may want to consider modifying the example config accordingly until a complete fix is implemented.

Thanks for your work in putting this together!

**Comment by dzg** [comment]
Updated, thanks!
